stages:
  - build

ubuntu-build:
  stage: build
  parallel:
    matrix:
      - UBUNTU_VERSION: "20.04"
      - UBUNTU_VERSION: "22.04"
  image: ubuntu:$UBUNTU_VERSION
  cache:
    paths:
      - ccache
  before_script:
    - export CCACHE_BASEDIR="$PWD"
    - export CCACHE_DIR="$PWD/ccache"
    - export CCACHE_COMPILERCHECK=content
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y
        build-essential
        ccache
        cmake
        gettext
        libcurl4-openssl-dev
        libguichan-dev
        libphysfs-dev
        libpng-dev
        libsdl2-dev
        libsdl2-image-dev
        libsdl2-mixer-dev
        libsdl2-net-dev
        libsdl2-ttf-dev
        libxml2-dev
        ninja-build
    - ccache --zero-stats || true
    - cmake -G Ninja -B build . -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
    - cmake --build build
    - ccache --show-stats

macos-build:
  stage: build
  allow_failure: true
  tags:
    - macos
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - cmake -G Ninja -B build .
    - cmake --build build
    - cd build
    - cpack -G DragNDrop
    - mv Mana-*.dmg ..
  artifacts:
    name: "macos-dmg-$CI_COMMIT_REF_SLUG"
    paths:
      - Mana-*.dmg
