stages:
  - build

ubuntu-build:
  stage: build
  parallel:
    matrix:
      - UBUNTU_VERSION: "20.04"
      - UBUNTU_VERSION: "22.04"
  image: ubuntu:$UBUNTU_VERSION
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y
        build-essential
        cmake
        gettext
        libcurl4-openssl-dev
        libguichan-dev
        libphysfs-dev
        libpng-dev
        libsdl2-dev
        libsdl2-image-dev
        libsdl2-mixer-dev
        libsdl2-net-dev
        libsdl2-ttf-dev
        libxml2-dev
        ninja-build
    - cmake -G Ninja -B build .
    - cmake --build build
