on: push

jobs:
  snap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: snapcore/action-build@v1
        id: snapcraft
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: snapcraft.log
          path: '/home/runner/.local/state/snapcraft/log/*.log'
      - uses: actions/upload-artifact@v4
        with:
          name: mana_amd64.snap
          path: ${{ steps.snapcraft.outputs.snap }}
